package Worker;


import Customer.*;
import Worker.*;
import Customer.*;
import Main.*;


import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class createWorker extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public createWorker() 
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Title2 = new javax.swing.JLabel();
        Title4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Title11 = new javax.swing.JLabel();
        emailEnter = new javax.swing.JTextField();
        lNameEnter = new javax.swing.JTextField();
        mobileEnter = new javax.swing.JTextField();
        createU = new javax.swing.JButton();
        Title12 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        fNameEnter = new javax.swing.JTextField();
        Title13 = new javax.swing.JLabel();
        certsEnter = new javax.swing.JTextField();
        Title35 = new javax.swing.JLabel();
        Title8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        abnEnter1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 710));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 710));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(550, 710));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(550, 710));
        kGradientPanel1.setLayout(null);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Create Worker");
        kGradientPanel1.add(Title2);
        Title2.setBounds(200, 60, 300, 80);

        Title4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Last Name:");
        kGradientPanel1.add(Title4);
        Title4.setBounds(20, 220, 210, 70);

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kGradientPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 420, 550, 10);
        jSeparator1.getAccessibleContext().setAccessibleDescription("");

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("Email:");
        kGradientPanel1.add(Title11);
        Title11.setBounds(20, 360, 210, 70);

        emailEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(emailEnter);
        emailEnter.setBounds(210, 380, 210, 30);

        lNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(lNameEnter);
        lNameEnter.setBounds(210, 240, 210, 30);

        mobileEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(mobileEnter);
        mobileEnter.setBounds(210, 340, 210, 30);

        createU.setBackground(new java.awt.Color(51, 51, 255));
        createU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createU.setText("Create Worker");
        createU.setActionCommand("");
        createU.setAutoscrolls(true);
        createU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        createU.setContentAreaFilled(false);
        createU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        createU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUActionPerformed(evt);
            }
        });
        kGradientPanel1.add(createU);
        createU.setBounds(320, 640, 210, 30);

        Title12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("First Name:");
        kGradientPanel1.add(Title12);
        Title12.setBounds(20, 180, 210, 70);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Mobile: ");
        kGradientPanel1.add(Title7);
        Title7.setBounds(20, 320, 210, 70);

        fNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(fNameEnter);
        fNameEnter.setBounds(210, 200, 210, 30);

        Title13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title13.setForeground(new java.awt.Color(255, 255, 255));
        Title13.setText("ABN:");
        kGradientPanel1.add(Title13);
        Title13.setBounds(10, 410, 210, 70);

        certsEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(certsEnter);
        certsEnter.setBounds(10, 500, 520, 130);

        Title35.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title35.setForeground(new java.awt.Color(255, 255, 255));
        Title35.setText("Certificates:");
        kGradientPanel1.add(Title35);
        Title35.setBounds(10, 450, 240, 70);

        Title8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("Pass-Word:");
        kGradientPanel1.add(Title8);
        Title8.setBounds(20, 270, 210, 70);

        jPasswordField1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(210, 290, 210, 30);

        abnEnter1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(abnEnter1);
        abnEnter1.setBounds(210, 430, 210, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 120, 120);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 710);

        setBounds(0, 0, 572, 751);
    }// </editor-fold>//GEN-END:initComponents

    private void createUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUActionPerformed
        String firstName = fNameEnter.getText();
        String lastName = lNameEnter.getText();
        String password = jPasswordField1.getText();
        long mobile = Long.valueOf(mobileEnter.getText().trim());
        String email = emailEnter.getText();
        long abnNum = Long.valueOf(abnEnter1.getText().trim());
        String certs = certsEnter.getText();
        
        
        
        WorkerRecord newWorker = Global.data.add_worker(firstName, lastName, password, mobile, email, abnNum,certs);
        currentUser user = new currentUser(newWorker.id,Global.data);
        Global.user = user;
        
        this.setVisible(false);
        WorkerMainFrame work = new WorkerMainFrame();
        work.setVisible(true);
        //take data and store into CSV File
        //move to customer bio 
        //take data and store into CSV File
        //move to customer bio 

    }//GEN-LAST:event_createUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title13;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title35;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JTextField abnEnter1;
    private javax.swing.JTextField certsEnter;
    private javax.swing.JButton createU;
    private javax.swing.JTextField emailEnter;
    private javax.swing.JTextField fNameEnter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lNameEnter;
    private javax.swing.JTextField mobileEnter;
    // End of variables declaration//GEN-END:variables

    private Object getFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
