package Worker;

import Customer.*;
import Worker.*;
import Customer.*;
import Main.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class sendQuote extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public sendQuote() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Title21 = new javax.swing.JLabel();
        serviceWorkName2 = new javax.swing.JTextField();
        costView2 = new javax.swing.JTextField();
        Title19 = new javax.swing.JLabel();
        Title20 = new javax.swing.JLabel();
        timeTill2 = new javax.swing.JTextField();
        aBn2 = new javax.swing.JTextField();
        Title22 = new javax.swing.JLabel();
        Title23 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        certs2 = new javax.swing.JTextArea();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 950));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(550, 710));
        kGradientPanel1.setLayout(null);

        Title21.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title21.setForeground(new java.awt.Color(255, 255, 255));
        Title21.setText("Service Worker Name:");
        kGradientPanel1.add(Title21);
        Title21.setBounds(20, 130, 240, 70);

        serviceWorkName2.setEditable(false);
        serviceWorkName2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(serviceWorkName2);
        serviceWorkName2.setBounds(310, 140, 160, 40);

        costView2.setEditable(false);
        costView2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(costView2);
        costView2.setBounds(310, 190, 160, 40);

        Title19.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title19.setForeground(new java.awt.Color(255, 255, 255));
        Title19.setText("Cost:");
        kGradientPanel1.add(Title19);
        Title19.setBounds(20, 180, 170, 70);

        Title20.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title20.setForeground(new java.awt.Color(255, 255, 255));
        Title20.setText("Approximite Time Till Arrival:");
        kGradientPanel1.add(Title20);
        Title20.setBounds(20, 230, 290, 70);

        timeTill2.setEditable(false);
        timeTill2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(timeTill2);
        timeTill2.setBounds(310, 240, 160, 40);

        aBn2.setEditable(false);
        aBn2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(aBn2);
        aBn2.setBounds(310, 290, 160, 40);

        Title22.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title22.setForeground(new java.awt.Color(255, 255, 255));
        Title22.setText("ABN:");
        kGradientPanel1.add(Title22);
        Title22.setBounds(20, 280, 240, 70);

        Title23.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title23.setForeground(new java.awt.Color(255, 255, 255));
        Title23.setText("Certificates:");
        kGradientPanel1.add(Title23);
        Title23.setBounds(10, 380, 240, 70);

        certs2.setEditable(false);
        certs2.setColumns(20);
        certs2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        certs2.setRows(5);
        jScrollPane6.setViewportView(certs2);

        kGradientPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(10, 440, 520, 140);

        create.setBackground(new java.awt.Color(51, 51, 255));
        create.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        create.setText("Send Quote");
        create.setActionCommand("");
        create.setAutoscrolls(true);
        create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        create.setContentAreaFilled(false);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        kGradientPanel1.add(create);
        create.setBounds(140, 590, 390, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 120, 120);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Send a Quote");
        kGradientPanel1.add(Title2);
        Title2.setBounds(140, 0, 300, 80);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 710);

        setBounds(0, 0, 572, 753);
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title19;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title20;
    private javax.swing.JLabel Title21;
    private javax.swing.JLabel Title22;
    private javax.swing.JLabel Title23;
    private javax.swing.JTextField aBn2;
    private javax.swing.JTextArea certs2;
    private javax.swing.JTextField costView2;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField serviceWorkName2;
    private javax.swing.JTextField timeTill2;
    // End of variables declaration//GEN-END:variables
}
