package Worker;

import Worker.*;
import Customer.*;
import Main.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class WorkerReport extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public WorkerReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Title5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        dash = new javax.swing.JTextField();
        expiryDayEnter = new javax.swing.JTextField();
        Title9 = new javax.swing.JLabel();
        expiryMonthEnter = new javax.swing.JTextField();
        expiryYearEnter = new javax.swing.JTextField();
        Title6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        incidentReports = new javax.swing.JTextArea();
        Title7 = new javax.swing.JLabel();
        Title11 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        incidentReports2 = new javax.swing.JTextArea();
        Title8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        incidentReports3 = new javax.swing.JTextArea();
        Title10 = new javax.swing.JLabel();
        fnameV = new javax.swing.JTextField();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        DropM = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 950));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setLayout(null);

        Title5.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText("Lighting Road Assistance");
        kGradientPanel1.add(Title5);
        Title5.setBounds(20, 0, 300, 80);

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel2.setkGradientFocus(750);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel2.setLayout(null);

        dash.setEditable(false);
        dash.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        dash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dash.setText("/");
        dash.setBorder(null);
        dash.setOpaque(false);
        kGradientPanel2.add(dash);
        dash.setBounds(140, 30, 30, 30);

        expiryDayEnter.setEditable(false);
        expiryDayEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryDayEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryDayEnter.setText("D");
        expiryDayEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDayEnterActionPerformed(evt);
            }
        });
        kGradientPanel2.add(expiryDayEnter);
        expiryDayEnter.setBounds(110, 30, 30, 30);

        Title9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title9.setForeground(new java.awt.Color(255, 255, 255));
        Title9.setText("Location:");
        kGradientPanel2.add(Title9);
        Title9.setBounds(270, 10, 100, 70);

        expiryMonthEnter.setEditable(false);
        expiryMonthEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryMonthEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryMonthEnter.setText("M");
        kGradientPanel2.add(expiryMonthEnter);
        expiryMonthEnter.setBounds(170, 30, 30, 30);

        expiryYearEnter.setEditable(false);
        expiryYearEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryYearEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryYearEnter.setText("Y");
        kGradientPanel2.add(expiryYearEnter);
        expiryYearEnter.setBounds(230, 30, 30, 30);

        Title6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("Incident Details:");
        kGradientPanel2.add(Title6);
        Title6.setBounds(10, 60, 250, 70);

        incidentReports.setEditable(false);
        incidentReports.setColumns(20);
        incidentReports.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports.setRows(5);
        jScrollPane1.setViewportView(incidentReports);

        kGradientPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 520, 140);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Repairs Given:");
        kGradientPanel2.add(Title7);
        Title7.setBounds(10, 260, 250, 70);

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("Rating:");
        kGradientPanel2.add(Title11);
        Title11.setBounds(10, 450, 100, 70);

        jRadioButton2.setText("1 Star");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(90, 470, 80, 29);

        jRadioButton3.setText("2 Stars");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(170, 470, 90, 29);

        jRadioButton4.setText("3 Stars");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(260, 470, 90, 29);

        jRadioButton5.setText("4 Stars");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(350, 470, 90, 29);

        jRadioButton1.setText("5 Stars");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(440, 470, 90, 29);

        incidentReports2.setEditable(false);
        incidentReports2.setColumns(20);
        incidentReports2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports2.setRows(5);
        jScrollPane3.setViewportView(incidentReports2);

        kGradientPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 520, 140);

        Title8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("Customer Feedback:");
        kGradientPanel2.add(Title8);
        Title8.setBounds(10, 500, 250, 70);

        incidentReports3.setEditable(false);
        incidentReports3.setColumns(20);
        incidentReports3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports3.setRows(5);
        jScrollPane4.setViewportView(incidentReports3);

        kGradientPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(10, 550, 520, 140);

        Title10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title10.setForeground(new java.awt.Color(255, 255, 255));
        Title10.setText("Date:");
        kGradientPanel2.add(Title10);
        Title10.setBounds(10, 10, 100, 70);

        fnameV.setEditable(false);
        fnameV.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel2.add(fnameV);
        fnameV.setBounds(370, 30, 160, 40);

        jTabbedPane1.addTab("Report 1", kGradientPanel2);

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel3.setkGradientFocus(750);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel3.setLayout(null);
        jTabbedPane1.addTab("Report 2", kGradientPanel3);

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel4.setkGradientFocus(750);
        kGradientPanel4.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel4.setLayout(null);
        jTabbedPane1.addTab("Report 3", kGradientPanel4);

        kGradientPanel5.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel5.setkGradientFocus(750);
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 51, 204));
        kGradientPanel5.setLayout(null);
        jTabbedPane1.addTab("Report 4", kGradientPanel5);

        kGradientPanel6.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel6.setkGradientFocus(750);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 51, 204));
        kGradientPanel6.setLayout(null);
        jTabbedPane1.addTab("Report 5", kGradientPanel6);

        kGradientPanel7.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel7.setkGradientFocus(750);
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel7.setLayout(null);
        jTabbedPane1.addTab("Report 6", kGradientPanel7);

        kGradientPanel8.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel8.setkGradientFocus(750);
        kGradientPanel8.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel8.setLayout(null);
        jTabbedPane1.addTab("Report 7", kGradientPanel8);

        kGradientPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 550, 880);

        DropM.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        DropM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu", "Edit Profile", "View Help Requests", "View Past Report Responses", "Log-out" }));
        DropM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DropM);
        DropM.setBounds(320, 10, 220, 60);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 950);

        setBounds(0, 0, 572, 1006);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void expiryDayEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDayEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDayEnterActionPerformed

    private void DropMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMActionPerformed

        if((String)DropM.getSelectedItem() == "Log-out")
        {
            this.setVisible(false);

            logInFrame log = new logInFrame();
            log.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            WorkerEditDetails ed = new WorkerEditDetails();
            ed.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Help Requests")
        {
            this.setVisible(false);

            ViewRequestHelp req = new ViewRequestHelp();
            req.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Past Report Responses")
        {
            this.setVisible(false);

            WorkerReport rep = new WorkerReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Menu")
        {
            this.setVisible(false);

            WorkerMainFrame work = new WorkerMainFrame();
            work.setVisible(true);
        }
    }//GEN-LAST:event_DropMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropM;
    private javax.swing.JLabel Title10;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JTextField dash;
    private javax.swing.JTextField expiryDayEnter;
    private javax.swing.JTextField expiryMonthEnter;
    private javax.swing.JTextField expiryYearEnter;
    private javax.swing.JTextField fnameV;
    private javax.swing.JTextArea incidentReports;
    private javax.swing.JTextArea incidentReports2;
    private javax.swing.JTextArea incidentReports3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    // End of variables declaration//GEN-END:variables
}
