package Main;


import Worker.*;
import Customer.*;
import javax.swing.JOptionPane;
import java.io.File;
import java.lang.ClassLoader;
import java.net.URL;
import java.net.MalformedURLException;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class logInFrame extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public logInFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Title1 = new javax.swing.JLabel();
        userEnter = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        logIn = new javax.swing.JButton();
        Title3 = new javax.swing.JLabel();
        Title4 = new javax.swing.JLabel();
        passEnter = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 1050));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(550, 1050));
        kGradientPanel1.setLayout(null);

        Title1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Lighting Road Assistance");
        kGradientPanel1.add(Title1);
        Title1.setBounds(230, 0, 390, 90);

        userEnter.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        userEnter.setBorder(null);
        userEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(userEnter);
        userEnter.setBounds(160, 360, 220, 40);

        create.setBackground(new java.awt.Color(51, 51, 255));
        create.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        create.setText("Create User");
        create.setActionCommand("");
        create.setAutoscrolls(true);
        create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        create.setContentAreaFilled(false);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        kGradientPanel1.add(create);
        create.setBounds(320, 870, 210, 60);

        logIn.setBackground(new java.awt.Color(255, 153, 0));
        logIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logIn.setText("Log-In");
        logIn.setActionCommand("");
        logIn.setAutoscrolls(true);
        logIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        logIn.setContentAreaFilled(false);
        logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logIn);
        logIn.setBounds(250, 480, 170, 50);

        Title3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Password:");
        kGradientPanel1.add(Title3);
        Title3.setBounds(50, 400, 210, 70);

        Title4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Username:");
        kGradientPanel1.add(Title4);
        Title4.setBounds(50, 340, 210, 70);

        passEnter.setText("jPasswordField1");
        passEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passEnterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(passEnter);
        passEnter.setBounds(160, 420, 220, 40);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 950);

        setBounds(0, 0, 572, 1006);
    }// </editor-fold>//GEN-END:initComponents

    private void userEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEnterActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        
        this.setVisible(false);
       
       createCustomer newcust = new createCustomer();
       newcust.setVisible(true);
        
        
    }//GEN-LAST:event_createActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        
        String Uname = userEnter.getText();
        String Pword = passEnter.getText();
        
        
        if(Uname != "AdminC" && Pword != "AdminC")
        {
             this.setVisible(false);
       
            customerMainFrame cust = new customerMainFrame();
            cust.setVisible(true);
        }
        else if(Uname == "AdminW" && Pword == "AdminW")
        {
             this.setVisible(false);
       
            WorkerMainFrame work = new WorkerMainFrame();
            work.setVisible(true);
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Inncorrect Username or Password");
        }
        
        
    }//GEN-LAST:event_logInActionPerformed

    private void passEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        ClassLoader loader = logInFrame.class.getClassLoader();
        URL url1 = loader.getResource("Main");
        try{
            URL url2 = new URL(url1.getProtocol(), url1.getHost(), url1.getPort(), url1.getFile() + "/CustomerRecords.csv", null);
            RandomDataGenerator randomData = new RandomDataGenerator();
            try
            {
                randomData.writeToCSV(url2);
            }
            catch(IOException f)
            {
                f.printStackTrace();
            }
                
        }
        catch(MalformedURLException e)
        {
            e.printStackTrace();
        }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JButton create;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField passEnter;
    private javax.swing.JTextField userEnter;
    // End of variables declaration//GEN-END:variables
}
