package Customer;


import Worker.*;
import Customer.*;
import Main.*;


import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.io.InputStream;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class addVehicle extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     * 
     */
    public Boolean enteredPicture = false;
    public String theFileLoc;
    public addVehicle() 
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        getProfilePic = new javax.swing.JButton();
        Title12 = new javax.swing.JLabel();
        fNameEnter = new javax.swing.JTextField();
        lNameEnter = new javax.swing.JTextField();
        Title4 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        mobileEnter = new javax.swing.JTextField();
        emailEnter = new javax.swing.JTextField();
        Title11 = new javax.swing.JLabel();
        createU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        DropM = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 710));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 710));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(550, 1050));
        kGradientPanel1.setLayout(null);

        getProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank-profile1.png"))); // NOI18N
        getProfilePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProfilePicActionPerformed(evt);
            }
        });
        kGradientPanel1.add(getProfilePic);
        getProfilePic.setBounds(20, 350, 500, 220);

        Title12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("Vehicle Model:");
        kGradientPanel1.add(Title12);
        Title12.setBounds(30, 120, 210, 70);

        fNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(fNameEnter);
        fNameEnter.setBounds(220, 140, 210, 30);

        lNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(lNameEnter);
        lNameEnter.setBounds(220, 180, 210, 30);

        Title4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Vehicle Make:");
        kGradientPanel1.add(Title4);
        Title4.setBounds(30, 160, 210, 70);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Year Manufactured:");
        kGradientPanel1.add(Title7);
        Title7.setBounds(30, 210, 210, 70);

        mobileEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(mobileEnter);
        mobileEnter.setBounds(220, 230, 210, 30);

        emailEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(emailEnter);
        emailEnter.setBounds(220, 270, 210, 30);

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("License Plate#:");
        kGradientPanel1.add(Title11);
        Title11.setBounds(30, 250, 210, 70);

        createU.setBackground(new java.awt.Color(51, 51, 255));
        createU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createU.setText("Add Vehicle");
        createU.setActionCommand("");
        createU.setAutoscrolls(true);
        createU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        createU.setContentAreaFilled(false);
        createU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        createU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUActionPerformed(evt);
            }
        });
        kGradientPanel1.add(createU);
        createU.setBounds(320, 600, 210, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmaller.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 80, 80);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Add Vehicle");
        kGradientPanel1.add(Title2);
        Title2.setBounds(100, 0, 300, 80);

        DropM.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        DropM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu", "Edit Profile", "View Vehicle/s", "Add Vehicle", "See Quotes", "See Upcoming Payments", "Make Report", "View Past Reports", "Log-out" }));
        DropM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DropM);
        DropM.setBounds(300, 10, 240, 60);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 750);

        setBounds(0, 0, 569, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void getProfilePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProfilePicActionPerformed

        Desktop desktop = null;
        if (Desktop.isDesktopSupported())
        {
            desktop = Desktop.getDesktop();
        }
        //String SelectPhotoURLString = Global.data.formatURLToString(Global.selectPhotoURL);
        //desktop.open(new File(SelectPhotoURLString));
        JFileChooser chooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = chooser.showOpenDialog(null);
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("jpeg images only","jpg");
        //chooser.setFileFilter(filter);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String extension = "";
            String absolutePath = selectedFile.getAbsolutePath();
            int i = absolutePath.lastIndexOf('.');
            if (i > 0) {
            extension = absolutePath.substring(i+1);
            }
            if(!extension.equals("jpg")){
                JOptionPane.showMessageDialog(null, "JPG files only");

            }
            else{
                System.out.println(selectedFile.getAbsolutePath());
                try
                {
                    Image img = ImageIO.read(selectedFile.toURL());
                    theFileLoc = absolutePath;
                    getProfilePic.setIcon(new ImageIcon(img));
                    enteredPicture = true;
                }
                catch(IOException f)
                {
                    f.printStackTrace();
                }
            }
        }



    URL url = null;
    /*try
    {
        url = new URL("C:\\Users\\codym\\Pictures\\818.png");
    }
    catch (MalformedURLException ex)
    {
        Logger.getLogger(createCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
    Toolkit kit = Toolkit.getDefaultToolkit();
    Image img = kit.createImage(url);
    this.setIconImage(img);*/

    }//GEN-LAST:event_getProfilePicActionPerformed

    private void createUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUActionPerformed

        String model = fNameEnter.getText().trim();
        String make = lNameEnter.getText().trim();
        int year = Integer.valueOf(mobileEnter.getText().trim());
        String licenseNum = emailEnter.getText();
        String fileLoc = "";
        if(enteredPicture){
            fileLoc = theFileLoc;
        }
        Global.data.add_vehicle(model, make, year, licenseNum,fileLoc);
        this.setVisible(false);
        customerMainFrame cust = new customerMainFrame();
        cust.setVisible(true);
        
        //take data and store into CSV File
        //move to customer bio
    }//GEN-LAST:event_createUActionPerformed

    private void DropMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMActionPerformed

        if((String)DropM.getSelectedItem() == "Menu")
        {
            this.setVisible(false);

            customerMainFrame cust = new customerMainFrame();
            cust.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "See Upcoming Payments")
        {
            this.setVisible(false);

            customerPayments payments = new customerPayments();
            payments.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Vehicle/s")
        {
            this.setVisible(false);

            viewVehicle pay = new viewVehicle();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Add Vehicle")
        {
            this.setVisible(false);

            addVehicle addV = new addVehicle();
            addV.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "See Quotes")
        {
            this.setVisible(false);

            seeQuotes pay = new seeQuotes();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Log-out")
        {
            this.setVisible(false);

            logInFrame log = new logInFrame();
            log.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Make Report")
        {
            this.setVisible(false);

            makeReport rep = new makeReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Past Reports")
        {
            this.setVisible(false);

            customerReports reps = new customerReports();
            reps.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
    }//GEN-LAST:event_DropMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropM;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title7;
    private javax.swing.JButton createU;
    private javax.swing.JTextField emailEnter;
    private javax.swing.JTextField fNameEnter;
    private javax.swing.JButton getProfilePic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lNameEnter;
    private javax.swing.JTextField mobileEnter;
    // End of variables declaration//GEN-END:variables

    private Object getFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
