package Customer;


import Worker.*;
import Customer.*;
import Main.*;


import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class CustomerEditDetails extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public CustomerEditDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        getProfilePic = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();
        fNameEnter = new javax.swing.JTextField();
        lNameEnter = new javax.swing.JTextField();
        Title12 = new javax.swing.JLabel();
        Title4 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        Title11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        emailEnter = new javax.swing.JTextField();
        mobileEnter = new javax.swing.JTextField();
        gold = new javax.swing.JRadioButton();
        silver = new javax.swing.JRadioButton();
        bronze = new javax.swing.JRadioButton();
        cNumberEnter = new javax.swing.JTextField();
        cNameEnter = new javax.swing.JTextField();
        expiryMonthEnter = new javax.swing.JTextField();
        dash = new javax.swing.JTextField();
        expiryYearEnter = new javax.swing.JTextField();
        cvvEnter = new javax.swing.JTextField();
        Title6 = new javax.swing.JLabel();
        Title10 = new javax.swing.JLabel();
        Title9 = new javax.swing.JLabel();
        Title8 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        createU = new javax.swing.JButton();
        DropM = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 950));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setLayout(null);

        getProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank-profile1.png"))); // NOI18N
        getProfilePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProfilePicActionPerformed(evt);
            }
        });
        kGradientPanel1.add(getProfilePic);
        getProfilePic.setBounds(20, 20, 210, 220);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Lighting Road Assistance");
        kGradientPanel1.add(Title2);
        Title2.setBounds(230, 70, 300, 80);

        fNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        fNameEnter.setText(Global.user.firstName);
        kGradientPanel1.add(fNameEnter);
        fNameEnter.setBounds(210, 260, 210, 30);

        lNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lNameEnter.setText(Global.user.lastName);
        kGradientPanel1.add(lNameEnter);
        lNameEnter.setBounds(210, 300, 210, 30);

        Title12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("First Name:");
        kGradientPanel1.add(Title12);
        Title12.setBounds(20, 240, 210, 70);

        Title4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Last Name:");
        kGradientPanel1.add(Title4);
        Title4.setBounds(20, 280, 210, 70);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Mobile: ");
        kGradientPanel1.add(Title7);
        Title7.setBounds(20, 350, 210, 70);

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("Email:");
        kGradientPanel1.add(Title11);
        Title11.setBounds(20, 390, 210, 70);

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kGradientPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 450, 550, 10);

        emailEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        emailEnter.setText(Global.user.email);
        kGradientPanel1.add(emailEnter);
        emailEnter.setBounds(210, 410, 210, 30);

        mobileEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        mobileEnter.setText(String.valueOf(Global.user.phoneNum)
        );
        mobileEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileEnterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(mobileEnter);
        mobileEnter.setBounds(210, 370, 210, 30);

        gold.setBackground(new java.awt.Color(255, 102, 0));
        gold.setForeground(new java.awt.Color(255, 255, 255));
        gold.setSelected(Global.user.membershipStatus == 3);
        gold.setText("GOLD");
        gold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gold.setBorderPainted(true);
        kGradientPanel1.add(gold);
        gold.setBounds(230, 490, 80, 19);

        silver.setBackground(new java.awt.Color(255, 102, 0));
        silver.setForeground(new java.awt.Color(255, 255, 255));
        silver.setSelected(Global.user.membershipStatus == 2);
        silver.setText("SILVER");
        silver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        silver.setBorderPainted(true);
        kGradientPanel1.add(silver);
        silver.setBounds(330, 490, 90, 19);

        bronze.setBackground(new java.awt.Color(255, 102, 0));
        bronze.setForeground(new java.awt.Color(255, 255, 255));
        bronze.setSelected(Global.user.membershipStatus == 1);
        bronze.setText("BRONZE");
        bronze.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bronze.setBorderPainted(true);
        kGradientPanel1.add(bronze);
        bronze.setBounds(440, 490, 100, 19);

        cNumberEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        cNumberEnter.setText(String.valueOf(Global.user.creditCardNum));
        kGradientPanel1.add(cNumberEnter);
        cNumberEnter.setBounds(230, 540, 210, 30);

        cNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        cNameEnter.setText(Global.user.nameOnCreditCard);
        kGradientPanel1.add(cNameEnter);
        cNameEnter.setBounds(230, 590, 210, 30);

        expiryMonthEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryMonthEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryMonthEnter.setText(Global.user.creditCardExpiryDate.split("/",-2)[0]
        );
        kGradientPanel1.add(expiryMonthEnter);
        expiryMonthEnter.setBounds(230, 630, 30, 30);

        dash.setEditable(false);
        dash.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        dash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dash.setText("/");
        dash.setBorder(null);
        dash.setOpaque(false);
        kGradientPanel1.add(dash);
        dash.setBounds(260, 630, 30, 30);

        expiryYearEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryYearEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryYearEnter.setText(Global.user.creditCardExpiryDate.split("/",-2)[1]);
        kGradientPanel1.add(expiryYearEnter);
        expiryYearEnter.setBounds(290, 630, 30, 30);

        cvvEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        cvvEnter.setText(String.valueOf(Global.user.cvv));
        kGradientPanel1.add(cvvEnter);
        cvvEnter.setBounds(230, 670, 90, 30);

        Title6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("CVV:");
        kGradientPanel1.add(Title6);
        Title6.setBounds(20, 650, 210, 70);

        Title10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title10.setForeground(new java.awt.Color(255, 255, 255));
        Title10.setText("Expiry Date:");
        kGradientPanel1.add(Title10);
        Title10.setBounds(20, 610, 210, 70);

        Title9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title9.setForeground(new java.awt.Color(255, 255, 255));
        Title9.setText("Name on Card:");
        kGradientPanel1.add(Title9);
        Title9.setBounds(20, 570, 210, 70);

        Title8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("Card Number:");
        kGradientPanel1.add(Title8);
        Title8.setBounds(20, 530, 210, 70);

        Title3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Member Ship Class: ");
        kGradientPanel1.add(Title3);
        Title3.setBounds(20, 470, 210, 70);

        createU.setBackground(new java.awt.Color(51, 51, 255));
        createU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createU.setText("Confirm Changes");
        createU.setToolTipText("");
        createU.setActionCommand("");
        createU.setAutoscrolls(true);
        createU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        createU.setContentAreaFilled(false);
        createU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        createU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUActionPerformed(evt);
            }
        });
        kGradientPanel1.add(createU);
        createU.setBounds(330, 630, 210, 60);

        DropM.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        DropM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu", "Edit Profile", "Add Vehicle", "See Upcoming Requried Payments", "View Past Reports", "Log-out" }));
        DropM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DropM);
        DropM.setBounds(330, 10, 210, 60);
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(460, 600, 80, 20);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 950);

        setBounds(0, 0, 572, 1006);
    }// </editor-fold>//GEN-END:initComponents

    private void getProfilePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProfilePicActionPerformed
        try
        {
            Desktop desktop = null;
            if (Desktop.isDesktopSupported())
            {
                desktop = Desktop.getDesktop();
            }

            desktop.open(new File("C:\\Users\\codym\\Pictures"));
        }
        catch (IOException ioe)
        {
            ioe.printStackTrace();
        }

        URL url = null;
        /*try
        {
            url = new URL("C:\\Users\\codym\\Pictures\\818.png");
        }
        catch (MalformedURLException ex)
        {
            Logger.getLogger(createCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        this.setIconImage(img);*/

    }//GEN-LAST:event_getProfilePicActionPerformed

    private void createUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUActionPerformed
        String firstName = fNameEnter.getText();
        String lastName = lNameEnter.getText();
        int mobileNumber = Integer.valueOf(mobileEnter.getText());
        String email = emailEnter.getText();
        int membershipStatus = 0;
        if (gold.isSelected())
        {
            membershipStatus = 3;
        }
        else if (silver.isSelected())
        {
            membershipStatus = 2;
        }
        else{
            membershipStatus = 1;
        }
        int ccNum = Integer.valueOf(cNumberEnter.getText());
        int cvv = Integer.valueOf(cvvEnter.getText());
        int ccMonth = Integer.valueOf(expiryMonthEnter.getText());
        int ccYear = Integer.valueOf(expiryYearEnter.getText());
        String nameOnCard = cNameEnter.getText();
        jLabel1.setText("saving info..");
        Global.data.edit_customer_profile(Global.user.id, firstName, lastName, mobileNumber, email, ccNum, cvv, ccMonth, ccYear, nameOnCard, membershipStatus);
        currentUser user = new currentUser(Global.user.id,Global.data);
        Global.user = user;
        jLabel1.setText("saved.");
//take data and store into CSV File
        //move to customer bio
    }//GEN-LAST:event_createUActionPerformed

    private void DropMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMActionPerformed

        if((String)DropM.getSelectedItem() == "Log-out")
        {
            this.setVisible(false);

            logInFrame log = new logInFrame();
            log.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Past Report")
        {
            this.setVisible(false);

            WorkerReport rep = new WorkerReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Add Vehicle")
        {
            this.setVisible(false);

            addVehicle addV = new addVehicle();
            addV.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "See Upcomming Required Payments")
        {
            this.setVisible(false);

            customerPayments pay = new customerPayments();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Menu")
        {
            this.setVisible(false);

            customerMainFrame cust = new customerMainFrame();
            cust.setVisible(true);
        }
    }//GEN-LAST:event_DropMActionPerformed

    private void mobileEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropM;
    private javax.swing.JLabel Title10;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JRadioButton bronze;
    private javax.swing.JTextField cNameEnter;
    private javax.swing.JTextField cNumberEnter;
    private javax.swing.JButton createU;
    private javax.swing.JTextField cvvEnter;
    private javax.swing.JTextField dash;
    private javax.swing.JTextField emailEnter;
    private javax.swing.JTextField expiryMonthEnter;
    private javax.swing.JTextField expiryYearEnter;
    private javax.swing.JTextField fNameEnter;
    private javax.swing.JButton getProfilePic;
    private javax.swing.JRadioButton gold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lNameEnter;
    private javax.swing.JTextField mobileEnter;
    private javax.swing.JRadioButton silver;
    // End of variables declaration//GEN-END:variables
}
