package Customer;

import Worker.*;
import Worker.*;
import Customer.*;
import Main.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class makeReport extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public makeReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        DropM = new javax.swing.JComboBox();
        dash = new javax.swing.JTextField();
        Title10 = new javax.swing.JLabel();
        expiryDayEnter = new javax.swing.JTextField();
        dash1 = new javax.swing.JTextField();
        expiryMonthEnter = new javax.swing.JTextField();
        expiryYearEnter = new javax.swing.JTextField();
        Title9 = new javax.swing.JLabel();
        fnameV = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        incidentReports2 = new javax.swing.JTextArea();
        Title6 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        incidentReports = new javax.swing.JTextArea();
        Title11 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        Title8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        incidentReports3 = new javax.swing.JTextArea();
        createU2 = new javax.swing.JButton();
        workerNameEnt = new javax.swing.JTextField();
        Title12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 950));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setLayout(null);

        DropM.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        DropM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu", "Edit Profile", "View Vehicle/s", "Add Vehicle", "See Quotes", "See Upcoming Payments", "Make Report", "View Past Reports", "Log-out" }));
        DropM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DropM);
        DropM.setBounds(300, 10, 240, 60);

        dash.setEditable(false);
        dash.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        dash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dash.setText("/");
        dash.setBorder(null);
        dash.setOpaque(false);
        kGradientPanel1.add(dash);
        dash.setBounds(200, 90, 30, 30);

        Title10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title10.setForeground(new java.awt.Color(255, 255, 255));
        Title10.setText("Date:");
        kGradientPanel1.add(Title10);
        Title10.setBounds(10, 70, 100, 70);

        expiryDayEnter.setEditable(false);
        expiryDayEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryDayEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryDayEnter.setText("D");
        kGradientPanel1.add(expiryDayEnter);
        expiryDayEnter.setBounds(110, 90, 30, 30);

        dash1.setEditable(false);
        dash1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        dash1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dash1.setText("/");
        dash1.setBorder(null);
        dash1.setOpaque(false);
        kGradientPanel1.add(dash1);
        dash1.setBounds(140, 90, 30, 30);

        expiryMonthEnter.setEditable(false);
        expiryMonthEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryMonthEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryMonthEnter.setText("M");
        kGradientPanel1.add(expiryMonthEnter);
        expiryMonthEnter.setBounds(170, 90, 30, 30);

        expiryYearEnter.setEditable(false);
        expiryYearEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        expiryYearEnter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiryYearEnter.setText("Y");
        kGradientPanel1.add(expiryYearEnter);
        expiryYearEnter.setBounds(230, 90, 30, 30);

        Title9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title9.setForeground(new java.awt.Color(255, 255, 255));
        Title9.setText("Location:");
        kGradientPanel1.add(Title9);
        Title9.setBounds(270, 70, 100, 70);

        fnameV.setEditable(false);
        fnameV.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(fnameV);
        fnameV.setBounds(370, 90, 160, 40);

        incidentReports2.setEditable(false);
        incidentReports2.setColumns(20);
        incidentReports2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports2.setRows(5);
        jScrollPane3.setViewportView(incidentReports2);

        kGradientPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 520, 100);

        Title6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("Incident Details:");
        kGradientPanel1.add(Title6);
        Title6.setBounds(10, 170, 250, 70);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Repairs Given:");
        kGradientPanel1.add(Title7);
        Title7.setBounds(10, 310, 250, 70);

        incidentReports.setEditable(false);
        incidentReports.setColumns(20);
        incidentReports.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports.setRows(5);
        jScrollPane1.setViewportView(incidentReports);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 520, 110);

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("Rating:");
        kGradientPanel1.add(Title11);
        Title11.setBounds(10, 460, 100, 70);

        jRadioButton2.setText("1 Star");
        kGradientPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(90, 480, 80, 23);

        jRadioButton3.setText("2 Stars");
        kGradientPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(170, 480, 90, 23);

        jRadioButton4.setText("3 Stars");
        kGradientPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(260, 480, 90, 23);

        jRadioButton5.setText("4 Stars");
        kGradientPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(350, 480, 90, 23);

        jRadioButton1.setText("5 Stars");
        kGradientPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(440, 480, 90, 23);

        Title8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("Customer Feedback:");
        kGradientPanel1.add(Title8);
        Title8.setBounds(10, 490, 250, 70);

        incidentReports3.setEditable(false);
        incidentReports3.setColumns(20);
        incidentReports3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        incidentReports3.setRows(5);
        jScrollPane4.setViewportView(incidentReports3);

        kGradientPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 540, 520, 110);

        createU2.setBackground(new java.awt.Color(51, 51, 255));
        createU2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createU2.setText("Make Report");
        createU2.setActionCommand("");
        createU2.setAutoscrolls(true);
        createU2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        createU2.setContentAreaFilled(false);
        createU2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kGradientPanel1.add(createU2);
        createU2.setBounds(320, 650, 210, 40);

        workerNameEnt.setEditable(false);
        workerNameEnt.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        kGradientPanel1.add(workerNameEnt);
        workerNameEnt.setBounds(220, 150, 160, 40);

        Title12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("Workerrs Name:");
        kGradientPanel1.add(Title12);
        Title12.setBounds(10, 130, 190, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmaller.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 80, 80);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Create a Report");
        kGradientPanel1.add(Title2);
        Title2.setBounds(90, 0, 300, 80);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 940);

        setBounds(0, 0, 572, 748);
    }// </editor-fold>//GEN-END:initComponents

    private void DropMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMActionPerformed

        if((String)DropM.getSelectedItem() == "Menu")
        {
            this.setVisible(false);

            customerMainFrame cust = new customerMainFrame();
            cust.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Vehicle/s")
        {
            this.setVisible(false);

            viewVehicle pay = new viewVehicle();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Add Vehicle")
        {
            this.setVisible(false);

            addVehicle addV = new addVehicle();
            addV.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "See Quotes")
        {
            this.setVisible(false);

            seeQuotes pay = new seeQuotes();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Log-out")
        {
            this.setVisible(false);

            logInFrame log = new logInFrame();
            log.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Make Report")
        {
            this.setVisible(false);

            makeReport rep = new makeReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Past Report")
        {
            this.setVisible(false);

            WorkerReport rep = new WorkerReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
    }//GEN-LAST:event_DropMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropM;
    private javax.swing.JLabel Title10;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JButton createU2;
    private javax.swing.JTextField dash;
    private javax.swing.JTextField dash1;
    private javax.swing.JTextField expiryDayEnter;
    private javax.swing.JTextField expiryMonthEnter;
    private javax.swing.JTextField expiryYearEnter;
    private javax.swing.JTextField fnameV;
    private javax.swing.JTextArea incidentReports;
    private javax.swing.JTextArea incidentReports2;
    private javax.swing.JTextArea incidentReports3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField workerNameEnt;
    // End of variables declaration//GEN-END:variables
}
