package Customer;


import Worker.*;
import Customer.*;
import Main.*;


import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author codym
 */
public class requestHelp extends javax.swing.JFrame {

    /**
     * Creates new form logInFrame
     */
    public requestHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Title2 = new javax.swing.JLabel();
        Title31 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        Title15 = new javax.swing.JLabel();
        fNameEnter = new javax.swing.JTextField();
        lNameEnter = new javax.swing.JTextField();
        Title4 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        mobileEnter = new javax.swing.JTextField();
        emailEnter = new javax.swing.JTextField();
        Title11 = new javax.swing.JLabel();
        Title12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inccidentReport1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inccidentReport2 = new javax.swing.JTextArea();
        fNameEnter1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Title17 = new javax.swing.JLabel();
        DropM = new javax.swing.JComboBox();

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator3.setAlignmentX(2.0F);
        jSeparator3.setAlignmentY(2.0F);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 950));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 950));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel1.setkGradientFocus(850);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setLayout(null);

        Title2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Lighting Road Assistance");
        kGradientPanel1.add(Title2);
        Title2.setBounds(20, 10, 300, 80);

        Title31.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title31.setForeground(new java.awt.Color(255, 255, 255));
        Title31.setText("Location:");
        kGradientPanel1.add(Title31);
        Title31.setBounds(20, 90, 240, 70);

        create.setBackground(new java.awt.Color(51, 51, 255));
        create.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        create.setText("Send Help Request");
        create.setActionCommand("");
        create.setAutoscrolls(true);
        create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        create.setContentAreaFilled(false);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        kGradientPanel1.add(create);
        create.setBounds(140, 870, 390, 60);

        Title15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title15.setForeground(new java.awt.Color(255, 255, 255));
        Title15.setText("Vehicle Modle:");
        kGradientPanel1.add(Title15);
        Title15.setBounds(10, 330, 210, 70);

        fNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(fNameEnter);
        fNameEnter.setBounds(200, 350, 210, 30);

        lNameEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(lNameEnter);
        lNameEnter.setBounds(200, 390, 210, 30);

        Title4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Vehicle Make:");
        kGradientPanel1.add(Title4);
        Title4.setBounds(10, 370, 210, 70);

        Title7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Year:");
        kGradientPanel1.add(Title7);
        Title7.setBounds(10, 440, 210, 70);

        mobileEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(mobileEnter);
        mobileEnter.setBounds(200, 460, 210, 30);

        emailEnter.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        kGradientPanel1.add(emailEnter);
        emailEnter.setBounds(200, 500, 210, 30);

        Title11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("Regostration:");
        kGradientPanel1.add(Title11);
        Title11.setBounds(10, 480, 210, 70);

        Title12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("Approximate Fault/s:");
        kGradientPanel1.add(Title12);
        Title12.setBounds(10, 530, 210, 70);

        inccidentReport1.setEditable(false);
        inccidentReport1.setColumns(20);
        inccidentReport1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        inccidentReport1.setRows(5);
        jScrollPane2.setViewportView(inccidentReport1);

        kGradientPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 580, 520, 130);

        inccidentReport2.setEditable(false);
        inccidentReport2.setColumns(20);
        inccidentReport2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        inccidentReport2.setRows(5);
        inccidentReport2.setText("Specify General Location and area with a streat or road and than a landmark, sign\nor house number.");
        jScrollPane3.setViewportView(inccidentReport2);

        kGradientPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 140, 520, 130);

        fNameEnter1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        fNameEnter1.setText("If unknown fill in bellow info");
        kGradientPanel1.add(fNameEnter1);
        fNameEnter1.setBounds(200, 290, 210, 30);

        jSeparator2.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator2.setAlignmentX(2.0F);
        jSeparator2.setAlignmentY(2.0F);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kGradientPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 540, 550, 10);

        jSeparator4.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator4.setAlignmentX(2.0F);
        jSeparator4.setAlignmentY(2.0F);
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kGradientPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 330, 550, 10);

        Title17.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title17.setForeground(new java.awt.Color(255, 255, 255));
        Title17.setText("Vehicle ID:");
        kGradientPanel1.add(Title17);
        Title17.setBounds(10, 270, 210, 70);

        DropM.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        DropM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu", "Edit Profile", "View Vehicle/s", "Add Vehicle", "See Quotes", "See Upcoming Payments", "View Past Reports", "Log-out" }));
        DropM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DropM);
        DropM.setBounds(300, 10, 240, 60);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 550, 950);

        setBounds(0, 0, 572, 1006);
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        

    }//GEN-LAST:event_createActionPerformed

    private void DropMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMActionPerformed

        if((String)DropM.getSelectedItem() == "Menu")
        {
            this.setVisible(false);

            customerMainFrame cust = new customerMainFrame();
            cust.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Vehicle/s")
        {
            this.setVisible(false);

            viewVehicle pay = new viewVehicle();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Add Vehicle")
        {
            this.setVisible(false);

            addVehicle addV = new addVehicle();
            addV.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "See Quotes")
        {
            this.setVisible(false);

            seeQuotes pay = new seeQuotes();
            pay.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Log-out")
        {
            this.setVisible(false);

            logInFrame log = new logInFrame();
            log.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "View Past Report")
        {
            this.setVisible(false);

            WorkerReport rep = new WorkerReport();
            rep.setVisible(true);
        }
        else if((String)DropM.getSelectedItem() == "Edit Profile")
        {
            this.setVisible(false);

            CustomerEditDetails edit = new CustomerEditDetails();
            edit.setVisible(true);
        }
    }//GEN-LAST:event_DropMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropM;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title15;
    private javax.swing.JLabel Title17;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title31;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title7;
    private javax.swing.JButton create;
    private javax.swing.JTextField emailEnter;
    private javax.swing.JTextField fNameEnter;
    private javax.swing.JTextField fNameEnter1;
    private javax.swing.JTextArea inccidentReport1;
    private javax.swing.JTextArea inccidentReport2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lNameEnter;
    private javax.swing.JTextField mobileEnter;
    // End of variables declaration//GEN-END:variables
}
